name: Generate Podcast Feeds
on: [push]
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: action/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyymal
      - name: Run Feed generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email github-action@github.com
          git add.
          git commit -m "Modified feed"
          git push
